### PR TITLE
Merge changes from miditones used in the Arduino/Teensy library (PaulStoffregen/Audio)

### PR DESCRIPTION
**Pull request by blackketter**
which includes a velocity output option

### CODE REVIEW

**Comment by LenShustek** [comment]
Nicely done. But I think that in line 952, "shifted_note" should be "trk->velocity".

**Comment by blackketter** [comment]
Good eye!  I’ll fix.

**Comment by blackketter** [comment]
BTW, while I’m happy to help keep things tidy, you might reach out to Paul and see if there might be a single master repository for miditones.

**Comment by LenShustek** [comment]
Merged, thanks.
I didn't know that Paul Stoffregen had forked this repository. That's fine with me if he wants to develop it independently, but I'll reach out to him to see what his intentions are.

**Comment by blackketter** [comment]
He didn’t fork the repo, but he did put miditones.c in the Audio library under extras.

**Comment by LenShustek** [comment]
Well, unless the historically glacial rate of changes increases, maybe we should leave things as they are for the time being. The code will get much more visibility at his site than at mine. Thanks for "keeping things tidy".

**Pull request merged**
