### PR TITLE
Fix compile errors on Linux (gcc run in default mode)

### PR DESCRIPTION
**Pull request by PaulStoffregen**
Simple, but without this the code won't build on Linux with the supplied makefile.

### CODE REVIEW

**Comment by MLXXXp** [comment]
I didn't have a problem building under Ubuntu Linux 16.04, using the supplied makefile, without this change.

**Comment by PaulStoffregen** [comment]
Definitely gives an error on Ubuntu 14.04

**Comment by MLXXXp** [comment]
It might be better to change Makefile

From:

`gcc -O2 -Wall -o miditones miditones.c`

to:

`gcc -std=c99 -O2 -Wall -o miditones miditones.c`

**Comment by LenShustek** [comment]
The ability to declare variables like that came in with the C99 standard. I like it because the variable scope is limited to the body of the "for", but being able to compile in more environments is more important.
Thanks, Paul.

**Pull request merged**
